### ISSUE TITLE
showing this error is it ssl problem

### ISSUE THREAD

**Issue by lyarinet** [EmulatorJS/EmulatorJS-netplay#25]
Network Error ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
emulator.min.js?v=31.5:1 Network Error ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
emulator.min.js?v=31.5:1 Network Error ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
emulator.min.js?v=31.5:1 Network Error ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
emulator.min.js?v=31.5:1 Network Error ProgressEvent {isTrusted: true, lengthComputable: false, loaded: 0, total: 0, type: 'error', …}
emulator.min.js?v=31.5:1 socket.io url is:  http://server.com:3000/

![Screenshot 2022-11-29 111851](https://user-images.githubusercontent.com/19821/204453759-765c7633-5793-4994-80dc-4f8f6d360228.png)

**Comment by ethanaobrien** [comment]
This isn't an ssl problem, this is a webrtc problem

**Comment by ethanaobrien** [comment]
Wait a second, no it isn't, I'm pretty sure this is because your server is not on. This is probably the same issue as in the other issue. Im closing this and we can debug the problem in the other issue
