### ISSUE TITLE
Netplay Seemingly Only Half-Working

### ISSUE THREAD

**Issue by Cattn** [EmulatorJS/EmulatorJS-netplay#26]
Okay, so I've deployed the server to a replit server for testing, Server turns on fine, shows up and works on my site fine, can make rooms, can see rooms (sometimes, more on that later in post), and can change room size/pass (sometimes)

Game I have been testing with: [Here](https://cattn.github.io/gba/launchpad.html?gameID=1251&gametitle=Contra&fav=true)
1. Rooms

These are hit or miss, the only way I can get rooms working, is with 2 tabs on the same device (me and one other person have confirmed this method) Otherwise, a few issues occur

a. Rooms will not show up at all 
   I create a room, it just doesn't show up for the other person
b. Unable to Join room
   Upon trying to join the room, it will display loading for a short second, then disappear, upon clicking button it will either say the room is full, or load for a short second and vanish again, it never actually joins the room. It does say sometimes on your screen (joiner) that there are 2 people in room, but it never will let you watch or do anything (you can still play on your own instance)
c. Rooms with password or different amount of max people
   Rooms with password straight up won't do anything when you hit join. Not much info is provided in console (Server or client) It does show it properly connecting to socket.io in console.
 
 
2. The server

a. Online Rooms
   It will never display a number above 0 for online rooms, even when connected properly between 2 tabs same device
   
 
 
 I can send any logs you need, just let me know what's needed

**Comment by Cattn** [comment]
I see netplay password already has been reported as bug under EmulatorJs/EmulatorJS bugs

**Comment by Cattn** [comment]
Forgot to include:

The demo on emulatorjs site does not work for us either, same results with things

**Comment by Cattn** [comment]
To add [This Issue](https://github.com/EmulatorJS/EmulatorJS/issues/69) may be the culprit, I'm not sure if it's been fixed, but it could be possible that we are both having issues because of this, (We have completely different PCs, but who knows) I will have some more people test to see

**Comment by ethanaobrien** [comment]
No, no it's not, this is because of webrtc. Either your computers cannot get a connection to the webrtc server or I just need to find a more reliable webrtc server. I can't fix this, this is a problem with your device/network/restrictions/limits

**Comment by ethanaobrien** [comment]
@Cattn Would you mind testing this again? I have upgraded the turn server to use another provider.

**Comment by Cattn** [comment]
Gotcha

**Comment by Cattn** [comment]
Alright tested it on phone and laptop with your demo, and it got further than before, (Would show both our names on a list) but would be stuck with loading message above, tried waiting for like 5-10min still there, happened on both phone and laptop same thing

**Comment by ethanaobrien** [comment]
Ok, so looks like we bypassed the webrtc issue

**Comment by Cattn** [comment]
Yep, seems like some other issue now

**Comment by ethanaobrien** [comment]
Yes, please open that as an issue in the emulatorjs repo if you dont mind. I'm very very glad I found a webrtc provider

**Comment by Cattn** [comment]
Will do, don't really have too much info about it but I will try to provide what there is
