### ISSUE TITLE
Netplay URL

### ISSUE THREAD

**Issue by Smevy** [EmulatorJS/EmulatorJS-netplay#31]
In the netplay documentation it shows you how to make a server but I think you should add that you need to also run cd "C:\Users\USERNAME\EmulatorJS-netplay" before you do npm install and npm run start. I know it's kind of obvious but I think It would be a good addition. Second I have a question about how to find the netplay url because when you host it shows no url, its probably really obvious I just don't know.

**Comment by ethanaobrien** [comment]
Part of #30
