### ISSUE TITLE
Question: Why did you add Twilo service to the netplay?

### ISSUE THREAD

**Issue by shaylevary** [EmulatorJS/EmulatorJS-netplay#36]
Hi,

I've noticed that on the latest netplay update, you've added Twilo service to your code.
Can I ask please what is the reason for it? Does it add any new feature?

 Thank you.

**Comment by ethanaobrien** [comment]
Yes. It used netplay before but I was able to use the netplay server to supply the needed data to any clients. Now, any server owners must do this on their own.
